version: '3.8'

services:
  traincomponentmanager:
    image: ${DOCKER_REGISTRY-}traincomponentmanager
    container_name: traincomponentmanager_app
    build:
      context: .
      dockerfile: TrainComponentManager/Dockerfile
    ports:
      - "80:8080"
      - "443:8081"
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver_db;Database=TrainDb;User ID=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;"
      ASPNETCORE_URLS: "http://+:8080;https://+:8081"
    depends_on:
      - sqlserver_db
    restart: always

  sqlserver_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_db
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: always

volumes:
  sqlserver_data: